### PR TITLE
Ukrainian

### PR DESCRIPTION
**Pull request by motomoto7**
Fixed apostrophe

### CODE REVIEW

**Comment by tibbi** [comment]
those apostrophes should actually be escaped, so the old version is good. I should be correcting it at copypasting, maybe I forgot it in some cases. If they are unescaped I cannot compile the code. Thanks

**Comment by motomoto7** [comment]
I don't entirely understand what you mean, sorry. 
Should the apostrophes be escaped by me or by something/someone else?
I cannot escape those because of specifics of Ukrainian language, there is no other option but to use them.
Don't know what you did but it looks to be fixed in Google Play long description at the moment. The apostrophes are there as they should be, the forward slash is not there. 
As far as I understand forward slash should be used always for strings translation. Should I use forward slash before an apostrophe further on in short/long description for Google Play? Should I escape apostrophes entirely in short/long description for Google Play? Correct me please if I am wrong.
Thanks a lot.
Screenshot_2019-06-05-13-13-58_1

**Comment by tibbi** [comment]
you should escape all apostrophes with a backward slash "\", no matter which string it is. Im copypasting the Google Play descriptions and removing the slashes manually. They have to be escaped in strings.xml file itself, else I cannot compile the code and Im getting errors.

**Comment by motomoto7** [comment]
I'm getting confused here.
Anyways I will try not to use apostrophes. If I do its a must case. If I use them I always add a slash ( / ) before an apostrophe ( /' ). 
Thanks a lot.

**Comment by tibbi** [comment]
use a backward slash "\", not a forward one.

**Comment by motomoto7** [comment]
Oh thanks 
I was somehow sonfused
Thanks again

**Pull request closed without merging**
