### PR TITLE
Implement editing audio tags for specific media files

### PR DESCRIPTION
**Pull request by KryptKode**
**Notes**
- implement editing audio tags for specific media files. 
- add function to rename audio files (for pre-Android 11 devices) alongside changing audio metadata like song title, song artist, song album names. 
- editing the metadata is done with the [`JAudioTagger`](https://bitbucket.org/ijabz/jaudiotagger/src/master/) library for its simplicity but newer versions only support Android 8 (API 26 and above). The maximum version we can use to support at least API 21 is 2.2.5.
- the changes written are persisted even after rescanning by the `MediaScannerConnection`. Other apps can see these changes in the file metadata from `MediaStore`. 
- The official `JAudioTagger` does not support editing metadata for `AAC`, `OPUS` files. However, does for `WAV` and `WMA` files but the changes written, are not detected by the android MediaStore. In the app, we disable the rename functionality for these files. `MP3`, `M4A`, `OGG` and `FLAC` files work well 
- should close [#298](https://github.com/SimpleMobileTools/Simple-Music-Player/issues/298)
- ~~[ this PR](https://github.com/SimpleMobileTools/Simple-Commons/pull/1192) should be merged before the project can be built due to an update to the commons library~~
- add new string `grant_change_metadata_permission= "Please grant the permission to modify audio properties"`  that displays on a toast when the user denies permission to modify a file.

### CODE REVIEW

**Comment by tibbi** [comment]
so this whole thing works on Android below 8 only? Or what changed for Android 9+?

**Comment by KryptKode** [comment]
> so this whole thing works on Android below 8 only? Or what changed for Android 9+?

It should work for API 21+ now using v2.2.5 of the JAudioTagger library.  See the [issue](https://bitbucket.org/ijabz/jaudiotagger/issues/149/some-nio-classes-are-unavailable-while). Any versions higher than 2.2.5 would not work on devices running on  Android 7 (API 25) and below.

**Comment by tibbi** [comment]
yeah, seems to work just fine, just a couple notes. Let's remove that new string, it isnt needed. 
1. if the user denies the permission, it is clear what went wrong. No need to show anything there
2. the Rename item should be visible everytime we are listing tracks, not just at the Tracks tab and after opening a playlist. It is missing in 2 cases. When you go at Albums tab, open an album, then select a track. Then if you go to the Artists tab and open an artist, then select a track at that screen

**Comment by KryptKode** [comment]
> yeah, seems to work just fine, just a couple notes. Let's remove that new string, it isnt needed.
> 
> 1. if the user denies the permission, it is clear what went wrong. No need to show anything there
> 2. the Rename item should be visible everytime we are listing tracks, not just at the Tracks tab and after opening a playlist. It is missing in 2 cases. When you go at Albums tab, open an album, then select a track. Then if you go to the Artists tab and open an artist, then select a track at that screen

Please check. I made the changes @tibbi

**Comment by tibbi** [comment]
ye should be good, thanks

**Comment by tibbi** [comment]
oh gosh, avoid copypasting such chunks of code between adapters though, move it into an extension or something. Ill move this one already, just saying for the future.

**Pull request merged**
