### PR TITLE
Add gapless playback strings

### PR DESCRIPTION
**Pull request by Naveen3Singh**

### CODE REVIEW

**Comment by tibbi** [comment]
shouldnt it be at the Current Track screen? Have you checked other apps?

**Comment by tibbi** [comment]
also if you add "Audio", it should be moved into Commons as it can be used in other apps too

**Comment by Naveen3Singh** [comment]
> shouldnt it be at the Current Track screen? Have you checked other apps?

Yes, it's generally in the main app settings. It's fairly a playback level setting so one doesn't need to switch it very often. It's more turn on and forget kinda thing.

**Comment by Naveen3Singh** [comment]
> also if you add "Audio", it should be moved into Commons as it can be used in other apps too

Do you have plans for any other setting in that category? The alternative category name is "Playback", some apps use that as well

**Comment by tibbi** [comment]
> > also if you add "Audio", it should be moved into Commons as it can be used in other apps too
> 
> Do you have plans for any other setting in that category? The alternative category name is "Playback", some apps use that

not really, I dont have any plans

**Comment by Naveen3Singh** [comment]
alright, I'm moving "Audio" to commons

**Comment by Naveen3Singh** [comment]
https://github.com/SimpleMobileTools/Simple-Commons/pull/1668

**Pull request merged**
