### PR TITLE
Add Genres tab

### LINKED ISSUE #372: [Feature Request] Add Genre
Add genre please and thanks for adding folders.

### PR DESCRIPTION
**Pull request by naveensingh**
Closes #372 

### Notes:
 - Added Genre tab. Disabled by default as not many people use it.
 - Genres can be sorted by title and track count.
 - Like albums and artists, tracks in a genre can also be added to the queue or a playlist using the options menu.
 - Sorting tracks in a genre will also impact the track sorting on the main Tracks tab
 - `Audio.Media.GENRE` and `Audio.Media.GENRE_ID` are available only on API level 30+ devices. To work around this, we are querying `content://media/external/audio/genres/all/members` directly to fetch genre information for each track on lower Android versions. We do not use `Audio.Genres.Members.getContentUri("external", genreId)` because fetching track info per genre can be slow when the device has many tracks/genres.

### CODE REVIEW

**Comment by naveensingh** [comment]
Tested on a couple of emulators and physical devices, and no issues were found. There is some boilerplate code due to album, artist, and genre fragments having the same layout, I'll remedy that in another PR soon.

**Comment by Yashraj254** [comment]
@naveensingh Is it acceptable to have six items on the bottom navigation bar?

**Comment by naveensingh** [comment]
In this case, we'll let the user decide. IIRC using more than 5 tabs is not recommended, as the text size could vary in different languages leading to a congested appearance but since this feature is optional, we don't need to enforce a limit of 5 tabs. We also allow using two tabs and that's not recommended either.

**Comment by Yashraj254** [comment]
Alright.

**Comment by tibbi** [comment]
looking good, thanks

**Comment by sezanzeb** [comment]
Oh how I am looking forward to getting this released. This is the missing piece for me

**Pull request merged**
