### PR TITLE
FIX #366 added audio focus feature

### LINKED ISSUE #366: add feature to play music in the background
Hello!

It would be really awesome to add an option in the settings to play the music in the background (to not require the android "audio focus")
Meaning that i can watch a video (without sound or at low volume) and listen to music in the background. If i try to do that now it will just pause the video and when i click to continue watching the video it pauses the music (obviously). As far as i read you have to make your audio playing function a service that doesn't require audio focus (something like this https://stackoverflow.com/a/43286485). Any response will be well appreciated since this is the one thing it is missing (maybe even i can help??)

PS: I really appreciate what you are doing with open source software for providing simple privacy friendly apps!

### PR DESCRIPTION
**Pull request by Yashraj254**
Fix #366 

Screenshot 2023-07-10 033928

Added _**Concurrent Playback**_ feature which is disabled by default to handle interruptions from other apps and if enabled it will allow concurrent playback with other apps.

### CODE REVIEW

**Comment by tibbi** [comment]
cant we show something as soon as possible at first install, maybe the mediastore files? It takes a really long time to show anything now.

**Comment by tibbi** [comment]
the settings string definitely has to be more descriptive, any suggestions?

**Comment by Yashraj254** [comment]
what about "Manage Audio Interruptions" or "Allow Concurrent Playback"

**Comment by tibbi** [comment]
lets make it `Allow concurrent playback with other apps`

**Comment by Yashraj254** [comment]
yeah sure.. so should i keep it enabled or disabled by default..

**Comment by tibbi** [comment]
keep the current version as default, so disabled

**Comment by Yashraj254** [comment]
alright.. it's done

**Comment by tibbi** [comment]
ok, @Naveen3Singh can you check if this is the proper way to avoid ducking?

**Comment by Naveen3Singh** [comment]
Three things:

- This won't work on Android 12 and above because the audio focus is now managed by the system. The system forces audio playback from an app to fade out. We could maybe workaround this by setting `AudioAttributes.CONTENT_TYPE_SPEECH` but we will probably get flagged for some policy violation on Google Play. If we want to enable this feature for Android 11 and below only, then a check should be added for that.

-  If we want to avoid ducking (lowering the volume) for notifications etc. the `config.allowConcurrentPlayback` check should also be added in the `AudioManager.AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK` case.
 
- The mentioned use case in #366 doesn't seem possible unless we either lower our player volume (duck) when another player starts or provide internal volume control.

**Comment by tibbi** [comment]
right, the check seems to have no effect on my Android 13. So thanks for the effort, but I dont want to add new options for low OS versions.

**Comment by Yashraj254** [comment]
well it works in latest android version too.. but only if we play the music in Simple Music Player first and then in some other app like spotify or a video player..  
if someone tries to play the music in some other app like spotify at first  and then tries to play in Simple Music Player.. then spotify music will be paused.. so one can just go back to that app and resume the music or video and both can be played concurrently... it's a small drawback of this feature

**Comment by Naveen3Singh** [comment]
> well it works in latest android version too.. but only if we play the music in Simple Music Player first and then in some other app like spotify or a video player..
if someone tries to play the music in some other app like spotify at first and then tries to play in Simple Music Player.. then spotify music will be paused.. so one can just go back to that app and resume the music or video and both can be played concurrently... it's a small drawback of this feature

that's by design and only true for Android 11 and below.
Android 12 and above versions will just silence Simple Music Player if we don't respect `AUDIOFOCUS_LOSS`: https://developer.android.com/media/optimize/audio-focus#audio-focus-12

**Comment by Yashraj254** [comment]
well that's odd.. i am using android 13 and it's working as i described

**Comment by Naveen3Singh** [comment]
could be some custom feature by the vendor. For example, Samsung has a **Dual App Sound** feature on some of their devices.

**Pull request closed without merging**
