### PR TITLE
Remove unnecessary nested layout

### PR DESCRIPTION
**Pull request by naveensingh**
Closes https://github.com/SimpleMobileTools/Simple-Music-Player/issues/440

https://github.com/SimpleMobileTools/Simple-Music-Player/assets/36371707/02f28ee4-aef5-4746-9a1c-4d4979ed0e27

### CODE REVIEW

**Comment by Naveen3Singh** [comment]
When there are many items and the currently playing track is towards the bottom of the list, it takes forever for `QueueActivity` to scroll to the track being played because we are using smooth scrolling. I tried speeding it up by overriding `LinearSmoothScrollers`'s `calculateSpeedPerPixel()` but it gets jerky and not smooth at all at high speeds so we need some other solution to fix that.

**Comment by tibbi** [comment]
people havent really reported lagging on this screen like in other places and I cannot really reproduce it either

**Comment by naveensingh** [comment]
Ok, fixed it now.

**Comment by tibbi** [comment]
looks good now

**Pull request merged**
