### PR TITLE
Dutch

### PR DESCRIPTION
**Pull request by ltGuillaume**
Note: EXIF data is used in (JPEG) files, not in audio files (with the exception of RIFF WAV). Do you mean ID3 here?

### CODE REVIEW

**Comment by ltGuillaume** [comment]
> Note: EXIF data is used in (JPEG) files, not in audio files (with the exception of RIFF WAV). Do you mean ID3 here?
This?

**Comment by tibbi** [comment]
not sure what you mean

**Comment by ltGuillaume** [comment]
In the English strings, it says:

> Modify file EXIF data like the song title and artist.

**Comment by tibbi** [comment]
Aha, I see. Dont worry, nobody reads these long descriptions anyway. They are there just to mention some keywords :)

**Comment by ltGuillaume** [comment]
Great! They're a b*tch to translate ;-) ;-)

**Comment by tibbi** [comment]
ye I know, but it helps

**Pull request merged**
